# Generated by Django 2.0.1 on 2018-04-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20180402_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='pin_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
