# Generated by Django 2.0.1 on 2018-04-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20180402_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
