# Generated by Django 2.0.1 on 2018-04-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20180402_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdetails',
            name='country',
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('O+', 'O+'), ('A-', 'A-'), ('B-', 'B-'), ('AB-', 'AB-'), ('O-', 'O-')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'OTHER')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='taluka',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
