# Generated by Django 2.0.1 on 2018-04-02 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_auto_20180402_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.CharField(choices=[('1', 'POOR'), ('2', 'BELOW AVERAGE'), ('3', 'AVERAGE'), ('4', 'ABOVE AVERAGE'), ('5', 'AMAZING')], default='1', max_length=20)),
                ('total_ratings', models.PositiveIntegerField(default=0)),
                ('speech_ratings', models.CharField(choices=[('1', 'POOR'), ('2', 'BELOW AVERAGE'), ('3', 'AVERAGE'), ('4', 'ABOVE AVERAGE'), ('5', 'AMAZING')], default='1', max_length=20)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('pin_code', models.IntegerField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('taluka', models.CharField(blank=True, max_length=100, null=True)),
                ('staff_strength', models.PositiveIntegerField(default=0)),
                ('cost_range', models.CharField(choices=[('1', 'CHEAP <200'), ('2', 'MODERATE <1000'), ('3', 'EXPENSIVE <10000'), ('4', 'FULL STAR > 10000')], default='4', max_length=100)),
                ('operation_facilty', models.BooleanField(default=False)),
                ('emergency_facility', models.BooleanField(default=False)),
                ('beds_count', models.PositiveIntegerField(default=10)),
                ('beds_occupied', models.PositiveIntegerField(default=10)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Hospital')),
            ],
        ),
    ]
