# Generated by Django 2.0.1 on 2018-04-03 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_hospitaldetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spam', models.BooleanField(default=False)),
                ('review', models.TextField(max_length=5000)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.Patient')),
            ],
        ),
    ]
