# Generated by Django 2.0.1 on 2018-04-10 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_allergiesasthma_bloodpressure_canser_heartdisease_kidney_liver_otherdisease'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(blank=True, max_length=5000, null=True)),
                ('data', models.TextField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=5000, null=True)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Disease')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.Hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Patient')),
            ],
        ),
        migrations.RemoveField(
            model_name='allergiesasthma',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='allergiesasthma',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='bloodpressure',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='bloodpressure',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='canser',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='canser',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='heartdisease',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='heartdisease',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='kidney',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='kidney',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='liver',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='liver',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='otherdisease',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='otherdisease',
            name='patient',
        ),
        migrations.DeleteModel(
            name='AllergiesAsthma',
        ),
        migrations.DeleteModel(
            name='BloodPressure',
        ),
        migrations.DeleteModel(
            name='Canser',
        ),
        migrations.DeleteModel(
            name='HeartDisease',
        ),
        migrations.DeleteModel(
            name='Kidney',
        ),
        migrations.DeleteModel(
            name='Liver',
        ),
        migrations.DeleteModel(
            name='OtherDisease',
        ),
    ]
